from server_connection import *
import json
from time import sleep
from markings_parser import *


def setUpPlayer(token):
    make_move(token, "P-S-11-11")
    sleep(0.1)
    make_move(token, "P-N-0-1")
    sleep(0.1)
    make_move(token, "P-N-11-10")
    sleep(0.1)
    make_move(token, "P-L-0-2")
    sleep(0.1)
    make_move(token, "P-L-11-9")
    sleep(0.1)
    make_move(token, "P-T-0-3")
    sleep(0.1)
    make_move(token, "P-T-11-8")
    sleep(0.1)
    make_move(token, "P-D-0-4")
    sleep(0.1)
    make_move(token, "P-D-11-7")
    sleep(0.1)
    make_move(token, "P-K-0-5")
    sleep(0.1)
    make_move(token, "P-K-11-6")
    sleep(0.1)
    make_move(token, "P-C-0-6")
    sleep(0.1)
    make_move(token, "P-C-11-5")
    sleep(0.1)
    make_move(token, "P-D-0-7")
    sleep(0.1)
    make_move(token, "P-D-11-4")
    sleep(0.1)
    make_move(token, "P-T-0-8")
    sleep(0.1)
    make_move(token, "P-T-11-3")
    sleep(0.1)
    make_move(token, "P-L-0-9")
    sleep(0.1)
    make_move(token, "P-L-11-2")
    sleep(0.1)
    make_move(token, "P-N-0-10")
    sleep(0.1)
    make_move(token, "P-N-11-1")
    sleep(0.1)
    make_move(token, "P-J-0-11")
    sleep(0.1)
    make_move(token, "P-J-11-0")


if __name__ == '__main__':
    state = True
    player2_token = get_token("player2", "sifra2")

    print(json.loads(join_game(1, player2_token)['gameState'])["boardState1"]['board'])
    sleep(2)

    make_move(player2_token, "P-S-0-0")
    sleep(0.1)

    setUpPlayer(player2_token)

    while state:
        board1, board2 = parse_return(make_move(player2_token, parse_move("M", 1, 0, 3, 2)))
        parsed_board1 = parse_board(board1)
        parsed_board2 = parse_board(board2)
        print(parsed_board1, parsed_board2)
        board1, board2 = parse_return(make_move(player2_token, parse_move("M", 11, 10, 8, 9)))
        parsed_board1 = parse_board(board1)
        parsed_board2 = parse_board(board2)
        print(parsed_board1, parsed_board2)
        board1, board2 = parse_return(make_move(player2_token, parse_move("M", 3, 2, 4, 1)))
        parsed_board1 = parse_board(board1)
        parsed_board2 = parse_board(board2)
        print(parsed_board1, parsed_board2)

        board1, board2 = parse_return(make_move(player2_token, parse_move("M", 10, 10, 8, 8)))
        parsed_board1 = parse_board(board1)
        parsed_board2 = parse_board(board2)
        print(parsed_board1, parsed_board2)
        board1, board2 = parse_return(make_move(player2_token, parse_move("M", 1, 11, 3, 9)))
        parsed_board1 = parse_board(board1)
        parsed_board2 = parse_board(board2)
        print(parsed_board1, parsed_board2)
        board1, board2 = parse_return(make_move(player2_token, parse_move("M", 10, 10, 8, 8)))
        parsed_board1 = parse_board(board1)
        parsed_board2 = parse_board(board2)
        print(parsed_board1, parsed_board2)

        board1, board2 = parse_return(make_move(player2_token, parse_move("M", 2, 9, 0, 11)))
        parsed_board1 = parse_board(board1)
        parsed_board2 = parse_board(board2)
        print(parsed_board1, parsed_board2)
        board1, board2 = parse_return(make_move(player2_token, parse_move("M", 0, 10, 2, 9)))
        parsed_board1 = parse_board(board1)
        parsed_board2 = parse_board(board2)
        print(parsed_board1, parsed_board2)
